require 'digest/sha1'
require 'bitcache/version'
require 'bitcache/config'
require 'bitcache/stream'
require 'bitcache/repository'
require 'bitcache/adapter'
require 'bitcache/utils'
require 'bitcache/encodings'
