.TH BITCACHE 7 "December 2010" "Bitcache 0\&.0\&.1" "Bitcache Manual"
.SH NAME
\fBbitcache\fP \-\- a content-addressable storage system
.SH SYNOPSIS
bit *
.SH DESCRIPTION
Bitcache is a distributed content-addressable storage (CAS) system.
It provides repository storage for bitstreams (colloquially known as blobs)
of any length, each uniquely identified and addressed by a digital
fingerprint derived through a secure cryptographic hash algorithm.
.SH ENVIRONMENT
TODO
.SH FILES
.I /etc/bitcache/bit.conf
.RS
The system-wide configuration file. See
.BR bitrc (5)
for further details.
.RE
.I ~/.bitrc
.RS
The per-user configuration file. See
.BR bitrc (5)
for further details.
.RE
.SH BUGS
Please report bugs to the mailing list at \fB<bitcache@googlegroups.com>\fP
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.SH SEE ALSO
.BR bitrc (5),
.BR bit (1),
.BR bitcached (8),
.BR libbitcache (3)
