.TH BITRC 5 "December 2010" "Bitcache 0\&.0\&.1" "Bitcache Manual"
.SH NAME
\fBbitrc\fP \-\- configuration files for Bitcache
.SH SYNOPSIS
TODO
.SH DESCRIPTION
TODO
.SH FILES
.I /etc/bitcache/bit.conf
.RS
The system-wide configuration file.
.RE
.I ~/.bitrc
.RS
The per-user configuration file.
.SH EXAMPLES
TODO
.SH SEE ALSO
.BR bitcache (7),
.BR bit (1),
.BR bitcached (8),
.BR libbitcache (3)
