.TH "BIT\-ID" 1 "December 2010" "Bitcache 0\&.0\&.1" "Bitcache Manual"
.SH NAME
\fBbit-id\fP \-\- identify a byte stream or file
.SH SYNOPSIS
\fBbit-id\fP [options] [\fIfile\fR \fI...\fR]
.SH DESCRIPTION
TODO
.SH EXIT STATUS
The \fBbit-id\fP utility exits with 0 on success, and with >0 if an error
occurs.
.SH EXAMPLES
TODO
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.SH SEE ALSO
.BR bitcache (7),
.BR bitrc (5),
.BR bit (1)
