.TH BIT 1 "December 2010" "Bitcache 0\&.0\&.1" "Bitcache Manual"
.SH NAME
\fBbit\fP \-\- the Bitcache command-line utility
.SH SYNOPSIS
\fBbit\fP [\-\-version] [\-\-help] COMMAND [ARGS]
.SH DESCRIPTION
TODO
.SH OPTIONS
.PP
\-\-version
.RS 4
Displays the Bitcache version and exits\&.
.RE
.PP
\-\-help
.RS 4
Displays command and option help and exits\&.
.RE
.SH FILES
.I /etc/bitcache/bit.conf
.RS
The system-wide configuration file. See
.BR bitrc (5)
for further details.
.RE
.I ~/.bitrc
.RS
The per-user configuration file. See
.BR bitrc (5)
for further details.
.RE
.SH EXIT STATUS
The \fBbit\fP utility exits with 0 on success, and with >0 if an error
occurs.
.SH EXAMPLES
TODO
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.SH SEE ALSO
.BR bitcache (7),
.BR bitrc (5),
.BR bit-id (1)
